js/src/jsapi.cpp
js/src/jsapi.h
js/src/jscntxt.h
js/src/jsgc.cpp

These APIs are no longer used by Servo, so there is no need to retain them here.

Remove cruft.

---

js/src/jsfriendapi.h

It is required if we want to call the uint8ClampedArray methods which are in jsfriendapi.rs

extern c blocks created around uint8ClampedArray method declarations

---

mfbt/double-conversion/more-architectures.patch
mfbt/double-conversion/utils.h

Tested for correctness as described in the comment.

Add AArch64 as an architecture supported by Double-Conversion.

---

makefile.cargo

This patch fixes three issues on Windows:
-   Set `$(CC)` properly and pass it to `js/src/configure`.
-   Set dummy `$(MOZ_TOOLS)` since `configure` requires non-empty
value.
-   Fix `$(OUT_DIR)` due to incompatibility between cargo (which uses
Windows native path e.g. `C:\path`) and msys make (which uses
`/c/path`).
With such modifications, it succeeded to build on Windows.
(Tested with: rustc 134e00be7 2015-02-09, cargo 9404539 2015-02-09)

Fix Windows build

---

js/src/jsfriendapi.h

Follow PR #25, enable all typed array function

enable all typed array function

---

makefile.cargo

Jemalloc needs to be disabled since jemalloc's definition of malloc_usable_size is different from the system's definition on OSX and Android. Ideally, we'd get SM to use Rust's jemalloc.

Also disable jemalloc on Android/Gonk

---

mozjs/js/public/MemoryMetrics.h
mozjs/js/src/vm/MemoryMetrics.cpp

The code is being backported from https://bugzilla.mozilla.org/show_bug.cgi?id=1181452. This change shouldn't land until the one in the Bugzilla bug has landed.

Backport memory reporting changes from bug 1181452

---

build.rs
makefile.cargo
mozjs/config/external/zlib/moz.build

The first patch fixes some configuration flags for ARM, which also means `jemalloc` is now disabled for all targets.
The second patch fixes zlib flags, which caused moz.build errors during cross compilation. I'm not sure if this is the correct way to solve this of if this works for all platforms, could you check it?
Requires servo/servo#6531
Part of servo/servo#6327
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/48)

Improve ARM cross compilation

---

makefile.cargo

r? @jdm 
This var will be set by some mach/.servobuild automation magic.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/62)

Check a CCACHE env var to add support

---

makefile.cargo

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/60)

Disable zealous GC in release builds.

---

build.rs
makefile.cargo
mozjs/config/baseconfig.mk
mozjs/config/external/icu/Makefile.in
mozjs/intl/icu/source/config/mh-mingw
mozjs/intl/icu/source/config/mh-mingw64
mozjs/js/src/gc/RootMarking.cpp
mozjs/js/src/jspubtd.h
mozjs/python/mozbuild/mozbuild/milestone.py

This is a set of changes needed to build mozjs under msys2/mingw64.
Core changes:
- Allow building with msys make
- Don't strip "lib" prefix from library names
- Use system nspr with correct lib names (nspr-config gives incorrect values)
- Force using native win32 python instead of the mingw64/msys python
I'm not really happy with these changes since these are all basically core m-c js files, and I don't think we could take some of these changes in m-c.  But, the majority of changes are correct or are resolving deeper issues in the m-c build system (e.g. the need to use the native win32 python instead of the msys one).
The ICU libprefix stuff can probably be resolved a different way, I just wasn't sure how to go about it.
[<img src="https://reviewable.io/review_button.png" height=40 …

Fix build under MSYS2/MINGW64

---

mozjs/config/recurse.mk

Bring it from upstream to fix an intermittent build break. 
Fixes servo#8416
r? @jdm
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/63)

Cherry-pick https://hg.mozilla.org/mozilla-central/rev/734e468e8274

---

Cargo.toml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/67)

Pin dependencies.

---

build.rs
makefile.cargo
mozjs/build/autoconf/nspr-build.m4
mozjs/js/src/configure
mozjs/js/src/jsapi.cpp
mozjs/js/src/jstypes.h
mozjs/js/src/moz.build
mozjs/js/src/prmjtime.cpp
mozjs/js/src/shell/js.cpp
mozjs/js/src/vm/PosixNSPR.cpp
mozjs/js/src/vm/PosixNSPR.h
mozjs/js/src/vm/WinNSPR.cpp
mozjs/mfbt/Types.h
mozjs/mozglue/build/moz.build

For some reason, gcc isn't generating public symbols for setTracingLocation if they're defined inline in the class declaration in the header.  There's probably an attribute we could apply or something, but this was the simplest way to get this to work.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/71)

Fix build for win32, remove --enable-gczeal that snuck back in

---

makefile.cargo

r? @Ms2ger 
This ensures that when SM has any floating point operations on Android in the C code, they're compiled to use SIMD instructions and/or FP registers instead of integer registers or fallback code. Big perf win.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/74)

Compile targeting modern ARM processors on Android for hardfloat

---

makefile.cargo

r? @Ms2ger @jdm 
The gold linker often either produces errors or incorrect binaries in cross-target builds. This is currently breaking the ARM64 builder.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/75)

Disable use of the gold linker on cross-targets

---

build.rs
makefile.cargo

- Add static MAKE_CMD variable for the make command
- replace instances of `make` with $(MAKE)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/80)

Compile successfully on FreeBSD

---

build.rs
etc/patches/fix-struct-class-winnspr.patch
etc/patches/no-pthread-posixnspr.patch
etc/patches/rust-bindgen-visibility.patch
makefile.cargo
mozjs/js/src/vm/PosixNSPR.h
mozjs/js/src/vm/WinNSPR.cpp
mozjs/mfbt/Types.h

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/82)

[msvc] allow mozjs to be built using MSVC on windows

---

build.rs
makefile.cargo

We need the moz tools to be at the start of the path, to not pick up random things along the way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/88)

Prepend MOZTOOLS_BIN to PATH, not append

---

README.md

* Mention building servo's bindgen fork
* Describe running `rust-mozjs/etc/bindings.sh` in more detail
r? @Ms2ger
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/95)

Expand upgrading instructions some more

---

Cargo.toml
etc/patches/Debugger-Promise-accessors.patch
etc/patches/More-Debugger-Promise-accessors.patch
makefile.cargo
mozjs/js/src/vm/Debugger.cpp
mozjs/js/src/vm/Debugger.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/89)

Enable native promises.

---

README.md

Now that https://github.com/servo/rust-mozjs/pull/302 landed.
r? @Ms2ger
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/100)

Update the upgrading instructions to use `bindings-all.py` instead of many manual steps

---

build.rs
makefile.cargo
mozjs/build/moz.configure/toolchain.configure
mozjs/js/src/builtin/Intl.cpp

Two of these apply to upstream; I've filed bug 1300925 and a comment on bug 1288313 for the WINNT issue (I should really file a separate bug).  The other two are rust-build-related fixes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/99)

smup fixes for Windows

---

mozjs/js/src/threading/posix/ConditionVariable.cpp

This patch is port from:
- https://hg.mozilla.org/mozilla-central/rev/43b1143f2930
- https://bugzilla.mozilla.org/show_bug.cgi?id=1284198
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/103)

Fix the build failure on macOS Sierra

---

makefile.cargo

See https://github.com/servo/servo/issues/13788.
I've tried a Servo build with this and have seen no problem, and now stuff like
localeCompare do the right thing.
r? @jdm
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/107)

Build with intl API.

---

makefile.cargo

This is the only problem I found while trying to build on NixOS (the usual problem from the unpatched virtualenv that SpiderMonkey bundles seems to have fixed itself so 🎉).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/109)

More portable way to set SHELL to bash.

---

makefile.cargo

The Visual C++ Build Tools package (which is freely provided by Microsoft) does not set `VSINSTALLDIR`. On the other hand, `VCINSTALLDIR` should as long as you have Visual C++ in any form.
https://social.msdn.microsoft.com/Forums/vstudio/en-US/198f6382-c5d2-4651-9135-0fde236793e7/environment-variables-in-visual-studio?forum=vcgeneral
Everything else is building, so close servo/servo#13325
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/111)

Change makefile.cargo to work with Build Tools

---

makefile.cargo

For Android x86 the `ANDROID_NDK` environment variable isn't passed
on correctly. Without this change it's not possible to compile the
`mozjs_sys` crate for Android x86, it would fail with:
Reexecuting in the virtualenv
checking for a shell... /bin/sh
checking for host system type... x86_64-pc-linux-gnu
checking for target system type... i686-pc-linux-android
checking for the Android toolchain directory... not found
...
configure: error: not found. Please check your NDK. With the current configuration, it should be in /platforms/android-9/arch-x86
With this change it's possible to compile it successfully for Android
x86 with:
PATH=$PATH:<x86-toolchain>/bin ANDROID_NDK=<android-ndk-r12b> cargo build --target i686-linux-android --verbose
---
This change is [<img …

Make it compile for Android x86 (i686)

---

mozjs/js/public/TraceKind.h

Import of https://hg.mozilla.org/mozilla-central/rev/59375acb5ae8. Fixes #116.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/117)

VS2017 doesn't require JS_DEPENDENT_TEMPLATE_HINT workaround.

---

makefile.cargo
mozjs/build/moz.configure/rust.configure
mozjs/js/src/old-configure
mozjs/js/src/threading/posix/ConditionVariable.cpp

See https://github.com/servo/servo/issues/11921 and https://github.com/servo/servo/pull/16769
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/118)

Support for Android armv7 and aarch64 target triples

---

build.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/121)

More explicit error if `make` isn't installed

---

build.rs
makefile.cargo

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/123)

Set MAKEFLAGS to CARGO_MAKEFLAGS for the make command

---

Cargo.toml

r? @asajeffrey
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/127)

Version bump for crates.io

---

Cargo.toml

Excludes tests and documentation, which isn't necessary to build, and therefore not necessary for the .crate tarball.
Excluding ICU causes the build to fail. We can investigate this later, if we feel the need. We now have a 50M limit for our crate on crates.io, so we should be able to publish now either way.
r? @SimonSapin
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/128)

Add `exclude` to `Cargo.toml`

---

Cargo.toml
makefile.cargo

If python2 seems to be a valid Python 2 interpreter, the configure
script will use it. Otherwise, it will fall back to python, as
previously.
We also bump the crate version so that this change can be propagated
further the dependency tree.
Closes #129.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/132)

Use python2 for the build whenever possible and bump the version.

---

Cargo.toml

This prevents publishing the crate and is unnecessary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/140)

Remove patch for libloading.

---

.travis.yml

This works around #152 by upgrading to a version of Rust that can build the most recent release of libz-sys.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/153)

Use a more recent stable version of Rust.

---

Cargo.toml
etc/patches/is_handled.patch
mozjs/js/src/jsapi.cpp
mozjs/js/src/jsapi.h

When trying to implement unhandled rejection in servo/servo#20755, I'd need to check the internal slot of Promise which is the step 4.1.1 for the spec of [notify about rejected promises](https://html.spec.whatwg.org/multipage/webappapis.html#notify-about-rejected-promises).
So, this PR will add the API to add the `GetPromiseIsHandled` method.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/150)

Support to get PromiseIsHandled internal slot in Promise

---

.gitignore

Makes `cargo publish` happier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/157)

Added mozjs/third_party/python/psutil/build and tmp to .gitignore

---

Cargo.toml
build.rs
etc/patches/bionic-glue-android-api-not-version.patch
etc/patches/configure-override-android-ndk-paths.patch
makefile.cargo
mozjs/build/moz.configure/android-ndk.configure
mozjs/mozglue/build/BionicGlue.cpp

This patch adds configuration for the Android NDK directory layout. It's used when building for the Magic Leap, which uses a very similar, but not quite identical, NDK.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/158)

Configure the Android NDK

---

README.md

The proposed `MOZTOOLS_PATH` no longer seems to be correct, as the current [MozillaBuild Package](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions/Windows_Prerequisites#MozillaBuild) doesn't create either `C:\mozilla-build\mozmake` or `C:\mozilla-build\yasm` directories. `mozmake.exe` and `yasm.exe` do exist in `C:\mozilla-build\bin`, though.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/145)

Correct MOZTOOLS_PATH

---

Cargo.toml

This is part of improving cross compiling support for Servo. See servo/servo#22571.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/174)

Bump bindgen version

---

Cargo.toml
appveyor.yml
build.rs
makefile.cargo
src/jsglue.cpp
src/jsglue.hpp
src/jsval.rs
vcvars.bat

These changes allow building for an x86 target on a x64 host. The changes to the JS glue are an extension of changes we've made in the past for other targets; we have just never run the affected tests for those targets before.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/176)

Support cross-compiling from x64->x86 on Windows.

---

appveyor.yml
etc/patches/broken-sdk.patch
mozjs/build/moz.configure/windows.configure

This will be a hard requirement in forthcoming spidermonkey upgrades, so let's try and switch it on ahead of time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/177)

Use clang-cl to build.

---

.travis.yml
Cargo.toml
etc/patches/libcpp-visibility-envvar.patch
mozjs/build/moz.configure/toolchain.configure

This patch allows the `_LIBCPP_INLINE_VISIBILITY` variable to be set by an environment variable, rather than just basing it on the compiler and target OS. It's needed for builds for Android targets which use the usual `libc++`, such as magicleap.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/180)

Add _LIBCPP_INLINE_VISIBILITY environment variable

---

.travis.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/188)

Fix macOS TravisCI builds

---

appveyor.yml
build.rs
makefile.cargo

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/190)

Support debugmozjs on Windows.

---

Cargo.toml
build.rs
src/jsglue.cpp
src/jsglue.hpp
src/jsimpls.rs

Running Servo's UWP app on an arm64 device, I encountered crashes creating global options where the app segfaulted when creating RealmOptions values. The crashes disappear when we allocate them on the heap instead of returning them by value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/191)

Work around Windows arm64 crash

---

etc/patches/uwp-pc-triple.patch
makefile.cargo
mozjs/build/moz.configure/init.configure
mozjs/build/moz.configure/rust.configure

The existing code that attempts to detect if a given target will allow compiling Rust code assumes that if multiple Rust targets target the same CPU that the triple's OS value will be unique (ie. x86_64-pc-windows-msvc vs. x86_64-pc-windows-gnu). This is no longer true with the introduction of x86_64-uwp-windows-msvc, but it's not enough to include the vendor string in the checks - the configure script is passed a different target (x86_64-windows-mingw32), and the python configuration code needs to reverse-engineer a Rust triple from it to use when compiling Rust code as part of the mozjs build. We bypass this issue by storing the target and host triples that Cargo makes available in the build script and using those value when the python configuration heuristics fail.
---
This change …

Support Rust configure when UWP targets are present

---

makefile.cargo

This is important when there are multiple versions of VS installed that the build system might end up trying to use. 2017 is the only supported version for building SpiderMonkey.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/197)

Force VS 2017 to be used on Windows.

---

Cargo.toml
build.rs
etc/patches/uwp-support.patch
makefile.cargo
mozjs/config/external/icu/common/moz.build
mozjs/js/moz.configure
mozjs/js/src/builtin/TestingFunctions.cpp
mozjs/js/src/ds/MemoryProtectionExceptionHandler.cpp
mozjs/js/src/gc/Memory.cpp
mozjs/js/src/jit/ProcessExecutableMemory.cpp
mozjs/js/src/js-config.h.in
mozjs/js/src/old-configure
mozjs/js/src/vm/CodeCoverage.cpp
mozjs/js/src/vm/DateTime.cpp
mozjs/js/src/vm/Time.cpp
mozjs/js/src/wasm/WasmSignalHandlers.cpp
mozjs/mfbt/Poison.cpp
mozjs/mfbt/RandomNum.cpp
mozjs/mfbt/WindowsVersion.h
mozjs/mozglue/misc/DynamicallyLinkedFunctionPtr.h
mozjs/mozglue/misc/StackWalk.cpp
mozjs/mozglue/misc/TimeStamp_windows.cpp
mozjs/mozglue/misc/WindowsMapRemoteView.cpp

These changes remove a bunch of forbidden API uses. I've tested a local build and it starts up and can successfully JIT some rAF code in a WebGL example.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/200)

Add cargo feature to build with UWP support.

---

Cargo.toml

… to pick up https://github.com/rust-lang/rust-bindgen/pull/1627
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/201)

Update rust-bindgen to 0.51

---

.gitignore
Cargo.toml
build.rs

The actual fix should live in psutil, but this is a good workaround meanwhile.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/203)

Skip `cargo:rerun-if-changed` for directories and everything in `.gitignore` (fixes #202)

---

Cargo.toml
makefile.cargo

Closes #204 
This supports opting out `--with-visual-studio-version=2017` by `--features vslatestinstalled`.
The name is from the script behavior:
https://github.com/servo/mozjs/blob/b2f83932fe9d361face14efd03f2465b9262e687/mozjs/build/moz.configure/toolchain.configure#L650-L652
(My original idea was to do `--with-visual-studio-version=2019` but the option currently only support `2017` as its value.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/205)

Support --features vslatestinstalled

---

build.rs
etc/patches/remove-cargo-version-check.patch
mozjs/build/moz.configure/rust.configure

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/207)

Make mozjs_sys cope with RLS (fixes #206)

---

etc/patches/uwp-target-native.patch
makefile.cargo
mozjs/build/moz.configure/rust.configure

This allows builds to complete when using aarch64-uwp-windows-msvc and x86_64-uwp-windows-msvc, which are more compatible with the corresponding pc targets than the SM build system would like to believe.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/210)

Support building with native UWP rustc targets.

---

build.rs

This is accessed by rust-mozjs so it can build its own jsglue.cpp.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/211)

Restore outdir build metadata

---

.travis.yml

This avoids TravisCI killing the job when some warnings on nightly cause the entire generated bindings file to be printed without newlines.

Format the bindings on CI.

---

build.rs

This adds RegExp flags to be used in JS_NewRegExpObject and JS_NewUCRegExpObject. Fixes #223.

Whitelist JSREG constants

---

.travis.yml
Cargo.toml
etc/patches/0019-Bug-1583854-Allow-builds-with-the-10.15-macOS-SDK.-r.patch
mozjs/build/moz.configure/toolchain.configure

Only one patch from upstream is relevant, the other is for a fix in a module that we don't use.
https://bugzilla.mozilla.org/show_bug.cgi?id=1583854

Allow building with 10.15

---

.travis.yml

Something changed in the TravisCI xenial environment recently that breaks bindgen when both the base clang-7 and clang-8 packages are installed. Compilation succeeds when clang-8 isn't installed.

Don't install clang-8 package on CI.

---

.travis.yml

We're prevented from merging any changes as long as there's no rustfmt available on nightly (https://rust-lang.github.io/rustup-components-history/).

Disable travis builds using nightly rustc.

---

Cargo.toml
makefile.cargo

This makes it easier to build with MSVC 2019 in the future.

Remove the requirement for MSVC 2017.

---

src/jsglue.hpp

I finally got around to finishing [form validation](https://github.com/servo/servo/pull/25447) in Servo and it looks like RegExp bindings got lost after SpiderMonkey update. This PR adds `js/RegExp.h` to `jsglue.hpp`.

Add RegExp bindings

---

build.rs

This significantly improves local build times for me when mozjs is rebuilt (such as with special features); previously we end up building all the C++ files sequentially. Fixes #244.

Use CARGO_MAKEFLAGS on Windows.

---

.gitignore
build.rs

Before this commit, running `cargo build` twice in a row runs the build script again. If with `CARGO_LOG=cargo::core::compiler::fingerprint=info`, the second run prints:
```
[2020-04-23T15:42:13Z INFO  cargo::core::compiler::fingerprint] stale: changed "/home/simon/projects/mozjs/mozjs/third_party/python/psutil/tmp/tmpc2PSEG.o"
[2020-04-23T15:42:13Z INFO  cargo::core::compiler::fingerprint]           (vs) "/home/simon/projects/mozjs/target/debug/build/mozjs_sys-9c51e5274ae91753/output"
[2020-04-23T15:42:13Z INFO  cargo::core::compiler::fingerprint]                FileTime { seconds: 1587656386, nanos: 37363833 } != FileTime { seconds: 1587656387, nanos: 633368104 }
[2020-04-23T15:42:13Z INFO  cargo::core::compiler::fingerprint] fingerprint error for mozjs_sys v0.68.1 …
```

Fix spurious rebuilds

---

src/jsglue.cpp
src/jsglue.hpp

This yields invalid codegen on Windows arm64 and causes crashes.

Don't return mozilla::Variant by value.

---

src/jsgc.rs

The lack of these barriers can cause memory corruption when these values are stored on the heap while a minor GC occurs.

Add GC barriers for JSString and JSScript heap values.

---

src/jsglue.cpp

All the StackCapture variants are plain old data, so we can avoid invoking the destructor when assigning via the pointer and do a memcpy instead.

Avoid invoking destructor on uninitialized StackCapture vlaues.

---

mozjs/build/moz.configure/toolchain.configure

Based on [this issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1682608), it looks like we can update mozjs to support up to macOS 11.1.

Updated to support macOS 11.1

---

build.rs

rather than based on the target os, which is not accurate for
*-windows-gnu.

Use MSVC-like flags on MSVC-like compilers

---

mozjs/build/moz.configure/toolchain.configure

Originally introduce by #258, but seems to be overwritten by accident by #265.

Restore support for macOS 11.1

---

build.rs

Seems like on aarch64 system, where gmake is missing shell return 127 [1]
as for missing binary, which isn't handled by Err exception.
[1] Exit code 127 means job's command can not be found or executed
Fixes: https://github.com/servo/servo/issues/28387
Signed-off-by: David Heidelberg <david@ixit.cz>

build: also verify that gmake command successed

---

build.rs

This bug caused needless rebuilds, because the (wrong)
rustfmt.toml path appears in a rerun-if-changed command,
triggering a rebuild even when nothing changed.

Fix rustfmt.toml path in build.rs

---

etc/patches/0022-py10.patch
mozjs/python/mozbuild/mozbuild/backend/configenvironment.py
mozjs/python/mozbuild/mozbuild/makeutil.py
mozjs/python/mozbuild/mozbuild/util.py
mozjs/testing/mozbase/manifestparser/manifestparser/filters.py

The abstract base classes in Python's collections module were moved to collections.abc. Importing them from collections is deprecated. With Python 3.10, importing them from collections does not work anymore.
Based on #292.

Update deprecated python imports

---

.github/workflows/rust.yml

They were broken by changes to Scoop (https://github.com/ScoopInstaller/Install#for-admin) and the release of a new MozillaBuild environment (https://github.com/servo/mozjs/issues/300).

Get Windows CI builds working again

---

makefile.cargo

While a NixOS system doesn't have /bin/bash but does have
/usr/bin/env, a Nix _builder_ has neither!
As pointed out by @Ms2ger in
https://github.com/servo/mozjs/pull/109#issuecomment-268814475
make will do a path search for you if only the executable
name is specified.

Even more portable way to set SHELL to bash

---

src/jsgc.rs

Resolves #306
- Adds GCMethods Implementation for `*mut Symbol`
- Rearranges GCMethods Implementations to follow order of RootKind Implementations
`ptr::null_mut()` as `GCMethods::initial` should not affect anything

Implemented GCMethods for Symbol

---

etc/patches/0023-no-winheap.patch
mozjs/memory/mozalloc/moz.build

Attempting to work around #312. Based on https://bugzilla.mozilla.org/show_bug.cgi?id=1280578 and https://bugzilla.mozilla.org/show_bug.cgi?id=1514122, it's unclear if we need it or not.

Disable winheap.cpp compilation.

---

build.rs
src/jsgc.rs
src/jsval.rs

Added `SymbolValue` and `Value::to_symbol` for converting to and from symbols and values.
Tested with an in-dev version of spiderfire and it seemed to work fine.

Added Symbol Functions

---

mozjs/src/jsgc.rs
mozjs/src/jsid.rs
mozjs/src/jsimpls.rs
rust-mozjs/src/glue.rs
rust-mozjs/tests/enumerate.rs

Resolves servo/rust-mozjs#544
There are a few inconsistent names in `jsid.rs` because `PropertyKey` and `jsid` are both names for the same thing, so I can change any of those if requested.
I have also deprecated the old functions which are in `mozjs::glue`, in favour of the new methods.
This also serves as preparation for future versions as stated in the [Migration Guide](https://github.com/mozilla-spidermonkey/spidermonkey-embedding-examples/blob/8dd70287d6214f24f7fcd1abd9d4f326ba7b4f62/docs/Migration%20Guide.md#property-keys).

Implemented Methods for PropertyKey

---

rust-mozjs/src/lib.rs

Allows `VoidId`, `IntId` and `SymbolId` to be used from `mozjs` directly.

Reexported jsid

---

.cargo/config
.github/workflows/rust.yml

I saw that a lot of dummy commits were made to test UWP building in https://github.com/servo/servo/pull/29079 (read: to test if mozjs actually compiles in servo), so the solution was obvious. Add UWP testing to mozjs so we can be more confident when landing changes to servo.
This PR also separates build scripts per OS host and removed testing on beta. UWP builds are run from nightly which is currently hardcoded in yaml file.

UWP builds in CI

---

.github/workflows/rust.yml

Now that we've upgraded to a recent spidermonkey, let's see if we still need to pin to python 3.9.

Build on latest python.

---

.github/workflows/rust.yml

Only temporary fix of: #327
I think the main reason of fail was System LLVM and Rust LLVM become out of sync.

Fix UWP builds

---

.github/workflows/rust.yml
mozjs/makefile.cargo

- use `cc` instead of `gcc` and `c++` instead of `g++` for fallback on linux
- format makefile
- pin window ci to rust 1.66 due to #334
- update nightly version used for UWP

Fix makefile style and fallback to general cc commands & temp windows builds fix

---

.github/workflows/rust.yml

optimizes Windows workflows and hopefully bypasses `rustup` problems from #342.

use dtolnay/rust-toolchain for UWP toolchain

---

.github/workflows/rust.yml
mozjs/build.rs
rust-mozjs/Cargo.toml
rust-mozjs/src/glue.rs
rust-mozjs/src/glue_wrappers.in
rust-mozjs/src/jsglue.cpp
rust-mozjs/src/rust.rs
rust-mozjs/tests/offthread.rs

https://github.com/servo/servo/issues/29214 reported a crash when compiling scripts off-thread on Windows. By using an outptr instead of a return value, we should avoid the ABI issue.

Fix broken offthread compilation on Windows

---

README.md
shell.nix

This patch makes it easier for NixOS users to work on mozjs by adding a shell.nix that should be exhaustive (it compiles ok under nix-shell --pure), and some advice to the README about Visual Studio Code and rust-analyzer.

README: add instructions for building on NixOS

---

.github/workflows/rust.yml

If installed LLVM and runners LLVM need to be in sync, the solution is clear: use runners LLVM, that way we also remove installing scoop/LLVM and speeding up builds.
Why hasn't it been done before? IIRC due to missing `libclang` or `llvm-config` or some other tool from LLVM that was not included in runners LLVM.
Should fix #302

Use runners llvm on windows

---

README.md
mozjs/etc/get_latest_mozjs.sh
mozjs/etc/get_mozjs.sh

This patch adds a guide to setting up editor support (clangd) for the C++ code, which is tricky because it means you need to develop your changes in an upstream SpiderMonkey checkout and import them here for local testing.
I’ve also changed the shebangs of get_mozjs.sh and get_latest_mozjs.sh for better NixOS compatibility.

README: add editor support guide

---

rust-mozjs/src/rust.rs

This will be needed to port https://searchfox.org/mozilla-central/rev/2d678a843ceab81e43f7ffb83212197dc10e944a/dom/bindings/BindingUtils.cpp#3667 to Servo in https://github.com/servo/servo/issues/29770.

Add API to (maybe) wrap a DOM object.

---

mozjs/src/jsglue.hpp

Trailing solidus in non-void tags is [not valid HTML5](https://html.spec.whatwg.org/multipage/parsing.html#parse-error-non-void-html-element-start-tag-with-trailing-solidus) and is specified to be treated as a start tag. This breaks the layout of the [generated Rust docs](https://doc.servo.org/mozjs/jsapi/index.html) and makes them very hard to read and use.
Replacing these with standard `div` tags fixes layout:

Fix rustbindgen tags in documentation

---

rust-mozjs/src/gc/collections.rs
rust-mozjs/src/gc/trace.rs
rust-mozjs/src/rust.rs

Porting tracers that were not ported in #352 so that servo could move to mozjs tracing infra.

Add missing tracers for servo

---

.github/workflows/rust.yml
README.md
mozjs/build.rs

Use a new MOZILLA_BUILD environment variable to set the PATH and
AUTOCONF variables. This makes it easier to set up the build and will
simplify the Servo build.

Windows: Set the PATH and AUTOCONF environment variables automatically

---

mozjs/makefile.cargo

1. Consistently use tabs.
2. Move all configure options next to each other
3. Use else if where possible.
4. Remove unused arguments to configure

Clean up the Cargo makefile

---

.github/workflows/rust.yml

Makes my life easier when testing changes.

Run CI only on master in upstream but everywhere in forks

---

.github/workflows/rust.yml

This is currently broken and it isn't going to be simple to fix.
Disabling this is better than always failing.

Disable the integrity check on CI

---

mozjs/src/jsimpls.rs

Methods are implemented according to https://searchfox.org/mozilla-central/source/js/public/Class.h#79-155 and https://searchfox.org/mozilla-central/source/js/src/jsapi.cpp#212-282.

Added Methods for ObjectOpResult

---

.github/workflows/rust.yml

This is essentially a revert of #369. It seems that skipping this
workflow for merge queue branches is causing PRs to merge without any
testing. See
https://github.com/servo/mozjs/actions/runs/5893101692
It's simply too finicky to maintain an upstream and downstream mode in
the same workflow when using the merge queue unfortunately.

Do not run the main workflow for non-master pushes

---

rust-mozjs/src/glue_wrappers.in
rust-mozjs/src/jsglue.cpp

Previously manual rust bindings have const ptr all over the place, now that bindings are auto generated those const need to be present in C++ code.

More const in jsglue

---

mozjs/build.rs

The warning was caused by `make` not being accessed after the initial assignment on Windows and immediately being reassigned.

Fixed build.rs Warnings

---

README.md

It's not so simple to build mozjs with MozillaBuild as you also need to install mozmake. Remove references to this installation method in README.md. Using MozTools is easier.
Fixes #397.

Remove MozillaBuild references in README.md

---

Cargo.toml

In preparation to update servo/webxr to the same version and dedup bindgen in Servo

Update bindgen to 0.68

---

.github/workflows/rust.yml
Cross.toml
README.md
mozjs/makefile.cargo
mozjs/tests/evaluate.rs

Partially resolves #401
This PR uses our [public docker images](https://github.com/orgs/servo/packages) for cross compiling. Minimal cross configuration is provided for easier usage of those docker images.

Add cross testing for linux arm64 & armhf

---

mozjs/src/generate_wrappers.sh

Make generate_wrappers work on dirty builds

---

mozjs-sys/Cargo.toml
mozjs-sys/makefile.cargo
mozjs/Cargo.toml

This will make prototyping streams in servo easier.

Hide js-streams behind feature

---

mozjs-sys/src/jsimpls.rs

The struct is used in functions like `StringToBigInt{,1}` and `DecodeStencil`, but can be quite annoying to construct since it has additional fields when `debugmozjs` is enabled.

Added Constructor for `mozilla::Range`

---

.github/workflows/rust.yml
mozjs-sys/build.rs

The error in #409 seems to be an issue between github action runner and homebrew.
There are lots of issue around it:
https://github.com/orgs/Homebrew/discussions/3895
https://github.com/actions/setup-python/issues/577
https://github.com/actions/runner-images/issues/6459
https://github.com/actions/runner-images/issues/6507
https://github.com/actions/runner-images/issues/2322
One of the workarounds is trying to relink the python package.

fix: macOS CI build errors

---

mozjs-sys/build.rs

There are [a few places in Servo](https://github.com/search?q=repo%3Aservo%2Fservo%20asbits_&type=code) where we need to check if two structs from mozjs-sys are equal, but since Bindgen doesn't automatically derive `PartialEq` by default, the code has to compare the inner `asBits_` field.
This PR tells Bindgen to automatically derive `PartialEq` where possible, to allow making such code simpler.

Derive `PartialEq` in `mozjs-sys` 

---

mozjs-sys/Cargo.toml

In #454 we got the need to have versioned mozjs-sys (even if unpublished) for artifact purposes so I proposed the following versioning for mozjs-sys (modeled after what we used before we give up on versioning):
`0.{SM-major}.{SM-minor}-#` where # is sequential number that is incremented for every C/C++ change in same SM version.
So we would start with `0.115.7-0` (we currently use SM 115.7) then for every C* change increment last number (`0.115.7-1`) until we move on to new SM `0.115.9-0` that would again start with new number.
CC @jdm @mrobinson @wusyong

Bump mozjs_sys version to 0.115.7-0

---

mozjs-sys/build.rs
mozjs-sys/etc/patches/0030-autoconf-add-ohos.patch
mozjs-sys/mozjs/build/autoconf/config.sub

Adds support for OpenHarmony OS.
A patch has been submitted upstream, pending review: https://lists.gnu.org/archive/html/config-patches/2024-02/msg00008.html
After the patch has been merged upstream, we can update `config.sub` in spidermonkey and drop this patch.

Add `-ohos` target support to autoconf

---

mozjs-sys/build.rs

This solves https://github.com/servo/servo/issues/31851 for me. The problem is that if libz is installed on system we add it's path to includes which causes problems. I think we do not need this as SM build system depends on pkg-config to find this.

Rely only on `pkg-config` to find zlib include directory

---

.github/workflows/release.yml
.github/workflows/rust.yml
README.md
mozjs-sys/build.rs

Blocked by #445 and probably need a CI from servo org to publish libmozjs.
This is the last step of #439. Everything should work now but it's based on my fork at the moment.

feat: add MOZJS_FROM_SOURCE 

---

.github/workflows/rust.yml
android-build
mozjs-sys/makefile.cargo

ANDROID_NDK_ROOT seems to be the more common environment variable
nowadays.

Use ANDROID_NDK_ROOT instead of ANDROID_NDK_HOME

---

mozjs-sys/build.rs

Downstream projects such as servo often also have many other C/C++ dependencies that are built with cc-rs, so having the Spidermonkey build respecting the same variables, makes configuring the downstream build easier and more predictable.
Closes #463

Respect cc-rs style environment variables when building SM

---

.github/workflows/rust.yml
mozjs-sys/build.rs

While compiling servo for OpenHarmony on a MacOS host, I noticed that readelf and objcopy apparently aren't chosen from the same directory as the clang c compiler, but needed to be in PATH for the configure script to pick them up. To allow users to set READELF and OBJCOPY explicitly, we should also read the relevant cc-rs environment variables.
An alternative would have been to inspect the configure scripts and find out why they don't look next to clang, but I'm not familiar enough with the configure script.

Also respect readelf and objcopy cc-rs variants

---

mozjs-sys/build.rs

Hey everyone!
Just tried to build mozjs locally and got a build error on the most recent main commit (369f2902e6481b8f237cca1652f56e61f508a0ad). Your CI seems to be building just fine though.
```
error[E0277]: the trait bound `Cow<'_, str>: AsRef<OsStr>` is not satisfied
--> mozjs-sys/build.rs:678:25
|
678 |             build.flag(&confdefs_path.to_string_lossy());
|                   ----  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `AsRef<OsStr>` is not implemented for `Cow<'_, str>`, which is required by `&Cow<'_, str>: AsRef<OsStr>`
|                   |
|                   required by a bound introduced by this call
|
= note: required for `&Cow<'_, str>` to implement `AsRef<OsStr>`
note: required by a bound in `Build::flag`
--> …
```

fix weird build error?

---

mozjs-sys/Cargo.toml
mozjs-sys/src/jsglue.cpp

This function is needed to be able to release the memory allocated by CreateWrapperProxyHandler from Rust after use.
This came up while investigating memory leaks in servo (servo/servo#32223). With this function added, we managed to create a proof of concept to fix the leak.
CC @rhetenor

Add DeleteWrapperProxyHandler

---

mozjs/src/rust.rs

Crash originally encountered in https://github.com/servo/servo/issues/32654
Before going into the `unsafe` block, make sure that we have a valid pointer
to hand to `StencilRelease()`. A null pointer previously resulted in a
segfault.
Tested using Servo:
1. Open news.baidu.com, which currently exposes this bug through a faulty
JS script being loaded (it's HTML and not JS).
2. Observe the segfault.
3. Apply the above fix.
4. Repeat, observe no crash.

Guard against null pointer when dropping Stencil

---

.gitattributes

As they are not vendored but generated using update.py, so let's mark them as such. This should also hide files from github diff in PRs (but not local diffs), so it should be easier to review SM bumps. We have integrity check to prevent misuses.
https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github

Mark mozjs-sys/mozjs as generated

---

README.md
mozjs-sys/Cargo.toml
mozjs-sys/build.rs

Stripping caused link error in script in servo's CI: https://github.com/servo/servo/pull/32769#issuecomment-2254893822

Fix esr128 windows artifact & MOZJS_ARCHIVE

---

mozjs-sys/Cargo.toml
mozjs-sys/build.rs
mozjs-sys/src/jsapi.cpp

Removing the two wrapped array buffer functions from the bindings also shortens imports (`mozjs::jsapi::<function>` as compared to `mozjs::jsapi::glue::<function>`).

Added Wrapper for NewArrayBufferWithContents

---

mozjs-sys/Cargo.toml
mozjs-sys/src/jsapi.cpp
mozjs-sys/src/jsapi.hpp

I forgot to add it to the header in #482, so here's a fix for that.

Added Wrapped NewArrayBufferWithContents to Header

---

.gitignore
mozjs/Cargo.toml
mozjs/src/conversions.rs
mozjs/tests/enforce_range.rs

While working on WebGPU I noticed that `EnforceRange` is not working right, per [specs](https://webidl.spec.whatwg.org/#abstract-opdef-converttoint), limits for 64bit values are 2**+-53 -+1.
See also relevant limits overrides in mozilla: https://searchfox.org/mozilla-esr128/rev/1aa97f9d67f7a7231e62af283eaa02a6b31380e1/dom/bindings/PrimitiveConversions.h#166

Fix enforcerange for 64bit numbers

---

mozjs-sys/Cargo.toml
mozjs-sys/etc/patches/0034-build__Add_compile_definition_for_ohos.patch
mozjs-sys/etc/patches/0035-Fix_mmap_for_JIT_on_HOS_Beta2.patch
mozjs-sys/mozjs/build/moz.configure/init.configure
mozjs-sys/mozjs/js/src/jit/ProcessExecutableMemory.cpp

The Security policy for JIT code is tightening on HarmonyOS . Beta 2 and newer require us to pass `MAP_EXECUTABLE` (internally same as `MAP_JIT`) to the committing mmap, otherwise it will fail.

Fix mmap for JIT code on HarmonyOS NEXT Beta 2

---

.github/workflows/rust.yml
mozjs-sys/src/jsglue.cpp

Adds C++ Formatting to the CI under the Integrity Check.
I suspect we could switch to `check-path=mozjs-sys/src` instead of `exclude-regex` since `mozjs` doesn't have any c++ anymore.

Added Clang Format Checks to CI

---

mozjs-sys/Cargo.toml
mozjs-sys/etc/patches/0036-Redirect_errors_to_hilog_on_OpenHarmony.patch
mozjs-sys/mozjs/build/moz.configure/init.configure
mozjs-sys/mozjs/config/system-headers.mozbuild
mozjs-sys/mozjs/memory/mozalloc/mozalloc_abort.cpp
mozjs-sys/mozjs/mfbt/Assertions.h
mozjs-sys/mozjs/mfbt/DbgMacro.h
mozjs-sys/mozjs/mozglue/misc/Debug.cpp
mozjs-sys/mozjs/nsprpub/pr/src/io/prlog.c

Similar to android, stderr output is generally not visible on OpenHarmony devices. Error messages should instead be logged via the `hilog` logging service. 
During normal operations, we can also do a workaround where we redirect stderr to hilog via a dedicated logging thread. 
However, for fatal errors such as failed assertions, which lead to the whole process dying, this solution is not sufficient, since the process might die before the logging thread has a chance to print the error message it received on `stderr`.

Log errors to hilog on OpenHarmony

---

mozjs-sys/Cargo.toml
mozjs-sys/build.rs

Currently, it's missing a space after the `-I{include_dir}`, so the user must manually specify ` {flags}` instead of `{flags}`.

Fixed Additional CPPFLAGS

---

Cargo.toml
mozjs-sys/Cargo.toml

No need for patching as 1.1.19 is released with needed fixes (mostly https://github.com/rust-lang/libz-sys/pull/199).

set libz-sys to 1.1.19

---

.clang-format
mozjs-sys/Cargo.toml
mozjs-sys/src/jsglue.cpp
mozjs/src/error.rs
mozjs/src/rust.rs
mozjs/tests/external_string.rs

I've added support for external latin1 strings, added in [bug 1576076](https://bugzilla.mozilla.org/show_bug.cgi?id=1576076). I've also updated the `.clang-format` based on [bug 1851529](https://bugzilla.mozilla.org/show_bug.cgi?id=1851529), and reformatted the C++ files accordingly.
Requires #474

Added Support for External Latin1 Strings

---

mozjs/src/typedarray.rs

Make TypedArray::update externally safe by adding unsafe block

---

mozjs-sys/src/jsimpls.rs

This PR is for fixing the issue in servo repo https://github.com/servo/servo/issues/29821.
We implemented a util function named [`callargs_is_constructing`](https://github.com/servo/servo/blob/20273b062af969152635306c3df2a3a1364ac4d1/components/script/dom/bindings/utils.rs#L629) in servo repo, but having an equivalent method in `JS::CallArgs` and using it should be clearer.
In this PR, a new method `is_constructing` is added to `JS::CallArgs`. It will be used in servo repo to replace all the usage of `callargs_is_constructing` function.

Add `is_constructing` method to `JS::CallArgs`

---

mozjs-sys/Cargo.toml
mozjs-sys/build.rs

If the user specifies `MOZJS_ARCHIVE`, that should be used no matter what, instead of checking for activated features.
The current system does not allow me to create an archive for testing locally with `debugmozjs` and use it, since it checks for that and returns `true`.
I can add some output if you want, but I wasn't sure about what to add.

Check for MOZJS_ARCHIVE before Building from Source

---

mozjs-sys/src/jsimpls.rs

This implements https://searchfox.org/mozilla-central/source/js/public/ScalarType.h#66, but we return None for `Type::MaxTypedArrayViewType` instead of crashing. This is much more safer then what is done in mozilla (see https://hg.mozilla.org/mozilla-central/rev/52377aae89ab697c60f663c36168e40f8e9445a4 for ex)

Impl byte_size on Scalar::Type

---

.github/workflows/rust.yml

Adding prebuilt artifacts should fix the OpenHarmony build on windows hosts, since it avoids needing to build spidermonkey from source (the spidermonkey build system seems to assume that on windows hosts, one will only cross-compile to other windows targets).
Additionally we can use this as a test for the github attestations api. 
It requires splitting the build and upload artifact into 2 different jobs, since the job that creates the artifact needs elevated permissions.
Write permissions can't and shouldn't be granted to forks, so I made the `ohos-release` job conditional.

Add prebuilt artifacts for OpenHarmony and test github attestions

---

mozjs-sys/Cargo.toml

Creates a release for:
-  Add prebuilt artifacts for OpenHarmony and test github attestions #501

Bump mozjs-sys to v0.128.0-10

---

mozjs-sys/Cargo.toml
mozjs-sys/build.rs

Allow the user to select the strip command via setting the STRIP environment variable (or the cc-rs variants of it).
For the OpenHarmony build the `ohos-build` script already sets `STRIP`, so this change also reduces the artifact size of the OpenHarmony release artifact.
Closes #508

Respect "STRIP" env variable for prebuilt artifact 

---

mozjs-sys/Cargo.toml
mozjs-sys/makefile.cargo

Save all input variables to the configure script, so that we can re-run it when necessary.
Closes #505

Reconfigure if configure inputs changed

---

mozjs-sys/Cargo.toml
mozjs-sys/src/jsgc.rs
mozjs-sys/src/jsglue.cpp
mozjs-sys/src/jsimpls.rs

The existing implementation for `Rooted<T>` is correct for most JS types that are rooted, but there's one significant case that is broken. `Rooted<T>` uses C++ template magic to change its base class depending on the type that it's templated over, and certain types that map to `RootKind::Traceable` [end up with a vtable](https://searchfox.org/mozilla-central/source/js/public/RootingAPI.h#923) that contains a custom tracing implementation, while other types do not have any such vtable.
These template shenanigans are very likely the reason why we have a handwritten `Rooted<T>` definition, since bindgen is not able to handle this situation. This PR makes the following changes:
* we introduce a vtable field into `Rooted<T>` which is zero-sized for types that do not have Traceable RootKind …

Fix unsound use of Rooted<T> with RootKind::Traceable

---

mozjs/tests/callback.rs
mozjs/tests/capture_stack.rs
mozjs/tests/enforce_range.rs
mozjs/tests/enumerate.rs
mozjs/tests/evaluate.rs
mozjs/tests/external_string.rs
mozjs/tests/jsvalue.rs
mozjs/tests/panic.rs
mozjs/tests/property_descriptor.rs
mozjs/tests/runtime.rs
mozjs/tests/stack_limit.rs
mozjs/tests/typedarray.rs
mozjs/tests/vec_conversion.rs

Discovered on work from https://github.com/servo/mozjs/pull/514 (failed before it landed: https://github.com/servo/mozjs/actions/runs/11548177590)

Use GCZeal in tests when run with debugmozjs

---

mozjs-sys/build.rs

Emit the `rerun-if-changed` lines for publicly documented MOZJS options.
Closes #516

Rebuild when `MOZJS_` options are changed

---

mozjs-sys/Cargo.toml
mozjs-sys/src/jsapi.cpp
mozjs-sys/src/jsglue.cpp
mozjs/src/generate_wrappers.sh
mozjs/src/jsapi_wrappers.in
mozjs/src/rust.rs

Fix #475
this will be needed to properly test streams rewrite in servo

Hide readablestream behind streams feature

---

mozjs/src/gc/macros.rs

This usage of initial() is safe because we're storing the result directly inside of a rooted location.

Hide call to unsafe method inside of an unsafe block in rooting macro.

---

.github/workflows/release-check.yml
README.md
mozjs-sys/Cargo.toml
mozjs-sys/build.rs

I tested this on my local fork (changed line 908 to point to `jschwe/mozjs`.
On my work machine the attestation takes around 500ms, but network is generally slow (downloading the 16MB artifact via curl takes somewhere between 20 and 60s for some reason)

Use github artifact attestations for the prebuilt artifacts

---

mozjs-sys/Cargo.toml
mozjs-sys/build.rs
mozjs-sys/tests/streams_available.rs

Fixes https://github.com/servo/servo/issues/34126, first commit contains tests.
try run: https://github.com/sagudev/servo/actions/runs/11659638946

Fix js-confdefs.h includes

---

mozjs-sys/Cargo.toml
mozjs-sys/src/jsglue.cpp

`-Winconsistent-missing-override` is enabled by default when compiling with clang.

jsglue.cpp: Fix -Winconsistent-missing-override

---

mozjs-sys/src/jsgc.rs
mozjs-sys/src/jsimpls.rs
mozjs/Cargo.toml
mozjs/examples/wasm.rs
mozjs/src/gc/collections.rs
mozjs/src/gc/root.rs
mozjs/src/gc/trace.rs
mozjs/src/lib.rs

It's far too easy to misuse by just creating a slice on the stack. Instead, we can add From implementations for constructs that are known to be safe (based on https://searchfox.org/mozilla-central/rev/8f423e3c79147c65d078589f3666dd25ffe80840/js/public/ValueArray.h#54-69). These changes also exposed that Servo was using a duplicate copy of the RootedVec code that included crown annotations and a `from_iter` implementation, so this PR also adds those features to support building Servo successfully with crown linting enabled.

Remove HandleValueArray::from_rooted_slice footgun

---

.github/workflows/build.yml
mozjs-sys/Cargo.toml

This will allow artifacts to be used on older systems (due to glibc).
Issue: https://github.com/servo/servo/pull/34562#issuecomment-2543342461

ci: Pin ubuntu to 22.04 in linux builder

---

mozjs/src/rust.rs
mozjs/tests/capture_stack.rs
mozjs/tests/iterate_stack.rs
mozjs/tests/jsvalue.rs

This adds `CapturedJSStack::for_each_stack_frame` which calls the provided closure for each element in the linked list of `SavedFrame`s. Unfortunately, I don't think there's an easy way to make this an iterator over `SavedFrame`s, because of the lifetime associated with a `RootedGuard`.
`for_each_stack_frame` is useful for providing js backtraces in functions like `console.trace`.

Allow iterating over the frames of a CapturedJSStack

---

mozjs/src/rust.rs
mozjs/tests/runtime.rs

This assertion fails in various tests and real browser usage, because it's still possible to call this API while shutdown is in progress. Instead of asserting against a valid use, we can use the type system to ensure that callers make informed choices.

Allow returning null context pointers from Runtime::get().

---

mozjs/src/gc/macros.rs

Copied from servo's `script::rooted_vec!`, but with `__root` instead of `root` and the correct `mozjs` paths.
Fixes #547

Fixed rooted_vec! Macro with Iterator Initialisation

---

mozjs-sys/build.rs

Adds `-D_CRT_USE_BUILTIN_OFFSETOF` for `jsglue` during the `bindgen` phase.
When building for `aarch64-pc-windows-msvc` with llvm 19, I had 12 errors as a result of `offsetof` not being `constexpr` compatible.
Examples of code which caused the errors:
<https://searchfox.org/mozilla-central/source/js/public/Proxy.h#459>
<https://searchfox.org/mozilla-central/source/mfbt/HashFunctions.h#367>
<details>
```shell
D:\a\spiderfire\spiderfire\target\aarch64-pc-windows-msvc\release\build\mozjs_sys-cbcf24600a385d3e\out\build\dist/include\mozilla/HashFunctions.h:367:27: error: constexpr function never produces a constant expression [-Winvalid-constexpr]
D:\a\spiderfire\spiderfire\target\aarch64-pc-windows-msvc\release\build\mozjs_sys-cbcf24600a385d3e\out\build\dist/include\mozilla/HashFunctions.h:371 …
```

Fixed Windows `jsglue` Builds with Define for Built-in `offsetof`

---

mozjs-sys/src/jsgc.rs
mozjs-sys/src/jsimpls.rs
mozjs/src/conversions.rs
mozjs/src/gc/root.rs

Wraps `Rooted::ptr` in `MaybeUninit` so it can safely be zero-initialized.
Fixes #548

Indicate to the compiler that Rooted<T> may be uninitialized

---

mozjs/src/rust.rs

Arc::strong_count doesn't come with memory ordering guarantees. As such it should be possible to destory the context multiple times with the previous version of this check. I haven't actually seen or attempted to force that to happen, just came across this while reading code.
See https://github.com/rust-lang/rust/issues/117485
Note: The new code is slightly slower (3 atomic operations when only 1 should be necessary, because it checks for weak pointers as well). I can't imagine we care.

Use Arc::get_mut instead of Arc::strong_count == 1

---

mozjs-sys/src/trace.rs

Traceable works under the assumption that only one thread will be looking at values. The entire purpose of `Arc` is to share things between threads. This never works (unless the Arc could be replaced by a Rc), and won't no matter how mutability is handled.
Nothing in this crate or servo uses this impl. Let's just delete this.

Arc should not be Traceable

---

mozjs-sys/Cargo.toml
mozjs-sys/src/glue.rs
mozjs-sys/src/lib.rs
mozjs-sys/src/trace.rs
mozjs/src/lib.rs
mozjs/tests/callback.rs

- `alloc_error_hook` has evidently been unused for... quite awhile. As far as I can tell the code should still work, up to adding back (conditionally) a nightly feature, so I've done that. 
- `EncodedStringCallback` is a function called from the C++ glue, it needs to be `extern "C"`. I've also marked this as an `unsafe` fn since it takes a raw pointer as an argument, and to be able to do anything with that it needs to be `unsafe`.
-  Remove an unused import, this one is my fault.
- jsapi has conflicting imports from two sets of bindgen, `js` and `JS` - currently this means that neither are imported. To silence these warnings, we pick one.
- Both have a `mod detail` with different contents, `detail::*` is also re-exported for both, so just pick one arbitrarily.
- `FrontendContext` exists …

Fix all the warnings

---

mozjs-sys/src/jsimpls.rs
mozjs/src/conversions.rs
mozjs/src/gc/root.rs

We're storing a `&mut Rooted<T>` in `RootedGuard` even though that pointer is aliased by the pointer held by the GC. This is... suspicious.
Background information: There are 2 proposed memory models for rust right now, [tree borrows](https://perso.crans.org/vanille/treebor/index.html) and [stacked borrows](https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/stacked-borrows.md). 
In the stacked borrows world, there's a stack-like structure containing "tags" describing which pointers have permission to access memory. Writing through a raw pointer will always invalidate all mutable references above it, and writing though a mutable reference will always invalidate all raw pointers above it. As such any ABAB interleaving off  writes accesses through a mutable pointer A and a …

RootedGuard<T> construction related unsoundness

---

mozjs/src/conversions.rs

As part of https://github.com/servo/servo/issues/36086 we need to support creating Rust Promise wrappers from JS values. We can do this through a layer of indirection for types that need to be wrapped inside of an Rc value: we introduce a new conversion trait that can be implemented by those types in other crates, which allows us to avoid the orphan rule.

Support creating Rc<T> values from JS values.

---

mozjs/src/gc/root.rs

Derive only derives these impls for types where the generics satisfy them, but shared references (and thus `Handle`) can implement them for any type `T`.
I've run into this a few times while playing around now, because `Cell` doesn't implement `Copy`. It's not entirely clear that users of the library will run into this, but at worst it doesn't hurt to define these generally.

Implement `Copy` and `Clone` for `Handle<T>` where `T: !Copy`

---

mozjs-sys/src/jsimpls.rs

Like with #572 and #573 this impl allows for improper aliasing with the GC. With this type it also allows for outright use after frees, since `JS::MutableHandle`, like a raw pointer, has no lifetime attached to it. Eventually that's a justification for removing the `Deref` impl as well, but once thing at a time.
There's only one use of this in servo, which is removed in the accompanying PR: https://github.com/servo/servo/pull/36161
Like with #572 and #573 I added an unsafe `as_mut` method, though it is unused locally this time as well as in servo. It feels like a reasonable escape hatch to share even if it isn't currently used.
Part of #569, and can be merged entirely independently from #572 and #573.

Remove DerefMut impl for `JS::MutableHandle`

---

mozjs/src/gc/root.rs

- We no longer construct `MutableHandle` via `deref_mut`. Doing so meant that the raw pointer in `MutableHandle` was only valid for as long as the mutable reference created in `deref_mut` would be. I.e. until the next time GC runs. This is an extension of #564, and doesn't require a change in public API.
- It removes the `deref_mut` impl entirely, as it's an unsafe footgun that isn't just marked as safe, but is silently invoked.
- Creates a helper `take` function for `RootedGuard<Option<T>>`, since that was the primary use of `DerefMut` in servo, and is a safe thing to do.
- It adds `allow_unrooted_interior` to `MutableHandle` because the accompanying servo PR requires that crown understand `MutableHandle` may point to things that must be rooted over GC passes.
Accompanying servo PR: …

Remove DerefMut impl for RootedGuard

---

mozjs/src/gc/root.rs

Removes the `deref_mut` impl, and replaces it with an unsafe `as_mut` method. As discussed in #569 (and other recent issues) `deref_mut` is unsafe since it aliases with the GC, and cannot be made safe or marked unsafe.
The accompanying servo change (servo/servo#36160) does not need the `as_mut` method, it feels like an appropriate escape hatch to include though.
It also includes a `MutableHandle::<Option<_>>::take` method, since like in #572 that's a safe method, and #572's servo change results in it being used on `MutableHandle`.
Independent from (the obviously related) #572 and the similar incoming PR for `JS::MutableHandle`. Doing these all at roughly the same time feels like the right move, since otherwise we might accidentally encourage someone to convert from one of these types …

Remove DerefMut impl for Mutable Handle

---

mozjs-sys/src/jsgc.rs
mozjs-sys/src/jsimpls.rs
mozjs/src/conversions.rs
mozjs/src/gc/macros.rs
mozjs/src/gc/root.rs

- Instead of storing `MaybeUninit<T>` in `Rooted<T>`, and initializing `RootedGuard` from a `&mut Rooted<T>`, store `T` in `Rooted<T>` and initialize `RootedGuard` from an `&mut MaybeUninit<Rooted<T>>`.
Currently every time we touch the data through `RootedGuard<T>`, we need to re-assert to the compiler that it is initialized. Adding one more thing to think about in an already complicated safety dance. By instead getting rid of the half initialized state, and passing the entire place in as uninitialized memory, this part of initialization can happen through entirely safe functions, and access never needs to worry about it.
- Correctly mark `ValueArray::get_ptr` as safe - it's doing things with the pointer that might be unsafe.
This lets us drop the unsafe block in `fn from(array: …

Refactor Rooted<T>

---

mozjs-sys/src/jsid.rs

This is needed to replicate https://searchfox.org/mozilla-central/rev/1f65969e57c757146e3e548614b49d3a4168eeb8/js/public/Id.h#183 for https://github.com/servo/servo/issues/34686.

Expose function to obtain a PropertyKey from a JSString.

---

mozjs-sys/src/jsapi.cpp
mozjs/src/jsapi_wrappers.in.rs
mozjs/src/rust.rs

This is needed for https://github.com/servo/servo/issues/34709, when we obtain a Nothing property descriptor from InvokeGetOwnPropertyDescriptor and need to pass it to SetPropertyIgnoringNamedGetter.

Support passing null property descriptor to SetPropertyIgnoringNamedGetter

---

mozjs-sys/Cargo.toml

https://github.com/servo/mozjs/pull/579/ modified the compiled C++ code, so we need to publish new compiled libraries.

Bump mozjs-sys version.

---

.github/workflows/build.yml
mozjs-sys/Cargo.toml
mozjs-sys/build.rs

Unified flags, as well as the usage of `cc` and `bindgen` for `jsapi` and `jsglue`.
Reorganised the `build.rs` primarily for the unification, but there are some changes in ordering and module organisation.
I'm not 100% sure on the ordering, so if you would like, that can be changed as well.
Resolves #435 through the removal of `-x c++` and addition of `--driver-mode=cl` on windows from the invocations of `bindgen`. Replaces #437.
Note the failures in `aarch64-pc-windows-msvc` are due to an error in llvm 18 https://github.com/llvm/llvm-project/pull/93235 (see https://github.com/rust-lang/rust-bindgen/issues/2842 also). LLVM 18.1.8 is installed on github actions runners for windows-2022. I have tested that LLVM 19 works correctly on spiderfire.

Unified Builds of jsapi and jsglue

---

mozjs-sys/src/jsglue.cpp

in the [SpiderMonkey Debugger API](https://firefox-source-docs.mozilla.org/js/Debugger/), hooks like [onNewGlobalObject()](https://firefox-source-docs.mozilla.org/js/Debugger/Debugger.html#onnewglobalobject-global) use an AutoDebuggerJobQueueInterruption to [switch to a new microtask queue](https://github.com/servo/mozjs/blob/b14aebff23ac4d5b0652060ef949334bda08b22f/mozjs-sys/mozjs/js/src/debugger/Debugger.cpp#L2834-L2841) and avoid clobbering the debuggee’s microtask queue. this in turn relies on JobQueue::saveJobQueue(), which is [not yet implemented in RustJobQueue](https://github.com/servo/mozjs/blob/b14aebff23ac4d5b0652060ef949334bda08b22f/mozjs-sys/src/jsglue.cpp#L83-L86).
this patch implements [saveJobQueue() and SavedJobQueue](https://github.com/servo/mozjs/blob/b14aebff23ac4d5b065 …

Implement saveJobQueue() for the SpiderMonkey Debugger API

---

mozjs/src/rust.rs

Implement a safe wrapper of `*mut JSAutoStructuredCloneBuffer` that Implements the Drop trait to prevent leakage.

Implement JSAutoStructuredCloneBufferWrapper

---

mozjs-sys/Cargo.toml
mozjs-sys/src/jsglue.cpp

in the [SpiderMonkey Debugger API](https://firefox-source-docs.mozilla.org/js/Debugger/), hooks like [onNewGlobalObject()](https://firefox-source-docs.mozilla.org/js/Debugger/Debugger.html#onnewglobalobject-global) use an AutoDebuggerJobQueueInterruption to [switch to a new microtask queue](https://github.com/servo/mozjs/blob/b14aebff23ac4d5b0652060ef949334bda08b22f/mozjs-sys/mozjs/js/src/debugger/Debugger.cpp#L2834-L2841) and avoid clobbering the debuggee’s microtask queue. this in turn relies on JobQueue::runJobs(), which is [not yet implemented in RustJobQueue](https://github.com/servo/mozjs/blob/b14aebff23ac4d5b0652060ef949334bda08b22f/mozjs-sys/src/jsglue.cpp#L76-L78).
this patch implements [runJobs()](https://github.com/servo/mozjs/blob/b14aebff23ac4d5b0652060ef949334bda08b22f/mozjs- …

Implement runJobs() for the SpiderMonkey Debugger API

---

mozjs-sys/Cargo.toml

The vendored version of icu_capi was bumped to 1.5.0 in the SM 137
update, so we need to update the version in the Cargo.toml too.
Additionally, we use `=1.5.0` to force selecting the same version as the vendored one.
The vendored icu_capi is never built, only its headers are used.

fix icu_capi version

---

mozjs-sys/Cargo.toml
mozjs-sys/build.rs

We don't need all default features, which are quite a few: https://github.com/unicode-org/icu4x/blob/599f3366f901eb0cc0af9de6c9de99998734bb8a/ffi/capi/Cargo.toml#L38
This reduces servo binary size by around 15% in production mode.
Companion PR: https://github.com/servo/servo/pull/38666

Remove unneeded icu_capi features

---

mozjs/src/error.rs

This is easy to trigger from code that throws a JS error and helpfully provides the original failed input (eg. `throw_js_error(cx, format!("\"{input}\" is not a valid ReadableStreamType value", 0)`). To avoid unnecessary allocations, we only perform the escaping if CString::new reports that the original string contains invalid bytes.

Replace null bytes in error text with escaped bytes.
