Cargo.toml

Move to a name without hyphens.

---

.gitignore
makefile.cargo

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/51)

Use NUM_JOBS to control make -j

---

Cargo.toml
build.rs
lib.rs

r? @metajack @mbrubeck 
CC @alexcrichton
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/52)

Better static linking

---

.travis.yml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/57)

Add a travis config.

---

.travis.yml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/58)

Move to travis for homu.

---

.travis.yml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/68)

Install gcc/g++ 4.8 on Travis.

---

makefile.cargo
mozjs/build/autoconf/nspr-build.m4
mozjs/js/src/configure
mozjs/js/src/moz.build
mozjs/js/src/old-configure
mozjs/js/src/old-configure.in
mozjs/js/src/vm/Time.cpp
mozjs/js/src/vm/WinNSPR.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/78)

Fix SMUP for Windows

---

.travis.yml

This cargo feature is currently only available in nightly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/83)

Use cargo's extra-verbose logging on travis.

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/90)

Add a README.

---

README.md

r? @Ms2ger
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/91)

Small update to upgrading instructions

---

README.md

r? @metajack
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/94)

Some more slight changes to the upgrading instructions

---

appveyor.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/101)

Set up AppVeyor.

---

etc/patches/Fix-the-build-for-macOS-Sierra.patch

Follow up https://github.com/servo/mozjs/pull/103
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/104)

add the original patch file of #103

---

.travis.yml

Also install yasm, to ensure osx builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/108)

Test more configurations on travis.

---

mozjs/build/autoconf/icu.m4
mozjs/js/src/old-configure

Cherry-picked from <https://hg.mozilla.org/mozilla-central/rev/ebcbf47a83e7d3b89460cf1c991b6be5a79a967b>.
CC <https://github.com/servo/servo/issues/15025>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/110)

Add brackets to icu.m4 for sed 4.3 compliance.

---

Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/114)

Add license field to Cargo.toml

---

build.rs
makefile.cargo

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/122)

Fix build on FreeBSD

---

.travis.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/125)

Update Homebrew on Travis

---

Cargo.toml

r? @asajeffrey
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/126)

Cargo.toml additions to allow for publishing on crates.io

---

Cargo.toml
build.rs

These changes allow my local Servo android build to complete.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/139)

Fix macOS/Android cross-compile.

---

mozjs/build/valgrind/valgrind.sh
mozjs/js/src/devtools/automation/macbuildenv.sh
mozjs/js/src/devtools/automation/winbuildenv.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/142)

Bug 1471541 - new tooltool url

---

Cargo.toml
src/jsimpls.rs

Let's kill regex 0.2 !
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/143)

Update bindgen and bump version

---

.travis.yml
Cargo.toml
build.rs

```
/Users/nox/src/mozjs/target/debug/build/mozjs_sys-0b48e14e1603d6a2/out/dist/include/mozilla/Span.h:32:10: fatal error: 'array' file not found
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/146)

Pass -stdlib=libc++ on Apple systems

---

Cargo.toml

r? @jdm
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/163)

Bump version to 0.61.4

---

makefile.cargo

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/165)

Add support for the aarch64 toolchains

---

Cargo.toml
etc/patches/disable-nspr-shared.patch
makefile.cargo
mozjs/config/external/nspr/moz.build

This should work around the duplicate DllMain that's appearing in https://github.com/servo/servo/pull/22856.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/170)

Disable all shared library code

---

Cargo.toml
makefile.cargo

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/173)

Add a cargo feature for profiling.

---

Cargo.toml
etc/patches/broken-sdk.patch
mozjs/build/moz.configure/windows.configure

This cherry-picks https://hg.mozilla.org/mozilla-central/rev/c085e1b32fb9.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/178)

Allow more recent SDK versions

---

.travis.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/175)

Use Xenial for TravisCI.

---

Cargo.toml
mozjs/js/src/util/NativeStack.cpp

Otherwise I can't build :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/183)

Cherry-pick the fix for bug 1533969.

---

makefile.cargo

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/184)

Pass correct targets for arm64 windows builds.

---

build.rs
etc/patches/nspr-emulation-windiws.patch
makefile.cargo
mozjs/js/src/vm/PosixNSPR.cpp
mozjs/js/src/vm/Time.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/185)

Don't build NSPR at all.

---

.gitattributes

As @jdm suggested in https://github.com/servo/servo/issues/23608.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/187)

Prevent CRLF conversion on Windows

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/mozjs/198)

[README] autoconf specific version is needed

---

etc/patches/0019-arm64-ion-bailout.patch
etc/patches/0020-Bug-1624072-Dont-clobber-destreg-in-visitMulI.patch
mozjs/js/src/jit/MacroAssembler.h
mozjs/js/src/jit/arm64/CodeGenerator-arm64.cpp
mozjs/js/src/jit/arm64/MacroAssembler-arm64-inl.h

https://phabricator.services.mozilla.com/D67485
https://phabricator.services.mozilla.com/D67742

Backport arm64 JIT performance improvements

---

.travis.yml

Same as https://github.com/servo/rust-mozjs/pull/500

Homebrew python2 fix

---

appveyor.yml

This matches the rest of our CI now.

Use VS 2019 in appveyor.

---

src/jsgc.rs

Remove Heap::handle_mut.

---

.github/workflows/rust.yml

Average build times are better.

Use GitHub Actions instead of Travis CI

---

etc/patches/0021-no-sdk-check.patch
mozjs/build/moz.configure/toolchain.configure

Remove macOS SDK check.

---

.github/workflows/rust.yml

#327 is getting in the way of other changes.

Disable UWP builds.

---

rust-mozjs/src/glue.rs

Will fix https://github.com/servo/servo/issues/30043

Fix mismatched ProxyTraps signature

---

mozjs/src/jsimpls.rs

Fixes mistake in #337 being merged too early.

Fixed Assertion in ObjectOpResult::fail

---

Cargo.toml
mozjs/build.rs

Use zlib from libz-sys if possible

---

.github/workflows/rust.yml
mozjs-sys/tests/evaluate.rs

wrappers integrity needs target directory to be populated, so it is run within linux jobs.

Check formatting and wrappers integrity in CI

---

mozjs-sys/build.rs
mozjs/build.rs

Fixed Windows Compilation with LLVM 17

---

mozjs/src/glue_wrappers.in
mozjs/src/jsapi_wrappers.in
mozjs/src/jsglue.cpp

- Updated Comment on MSVC Non-POD Return Values

Added Glue for GetRegExpFlags

---

.github/workflows/rust.yml

Runs CI every week to catch runner/rust changes.
Includes a fix for mac CI.

Fix Mac CI and schedule a workflow run weekly

---

mozjs-sys/etc/patches/0029-fix-ld64-detection.patch
mozjs-sys/mozjs/build/moz.configure/toolchain.configure

This should solve https://github.com/servo/mozjs/pull/427

Fix ld64 detection

---

Cargo.toml
mozjs-sys/Cargo.toml

A newer version of libz-sys was released.

Remove libz-sys patch

---

.github/workflows/dco-merge-group.yml

Same as in servo: https://github.com/servo/servo/pull/33290
DO not forget to also allow DCO check from any source per: https://github.com/servo/servo/pull/33308#issuecomment-2327919183

CI: Hack around DCO not in MQ

---

mozjs/src/rust.rs

https://github.com/servo/servo/issues/33759

Add `ThreadSafeJSContext`

---

mozjs-sys/src/jsapi.cpp

Fix recursive NewArrayBufferWithContents

---

mozjs/src/gc/root.rs

Make MutableHandle::new pub(crate)

---

.github/workflows/build.yml

ci: upgrade mozilla/sccache-action to v0.0.8

---

mozjs/src/gc/root.rs

Sorry about this, my last set of PRs weren't quite as independent as I thought.

Remove unused import

---

mozjs-sys/Cargo.toml
mozjs-sys/build.rs

Allow disabling the from source build explicitly.

Respect MOZJS_FROM_SOURCE=0

---

.github/workflows/build.yml
.github/workflows/release-check.yml
mozjs-sys/Cargo.toml

We want to test all android targets we have in servo.

Add more android targets to CI and release android artifacts

---

mozjs-sys/src/jsgc.rs

Add crown::unrooted_must_root_lint::must_root to Heap

Add crown::unrooted_must_root_lint::must_root to Heap

---

.github/workflows/build.yml
mozjs/src/generate_wrappers.sh

As noted in https://github.com/servo/mozjs/pull/584#discussion_r2246112882

ci: Check wrappers integrity more strictly
